services:
  frontend-dev:
    build: ./frontend
    ports:
      - '${FRONTEND_DEV_PORT:-3000}:${FRONTEND_DEV_PORT:-3000}'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --port ${FRONTEND_DEV_PORT:-3000} --host

  storybook-dev:
    build: ./frontend
    ports:
      - '${STORYBOOK_DEV_PORT:-4000}:${STORYBOOK_DEV_PORT:-4000}'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run storybook -- --port ${STORYBOOK_DEV_PORT:-4000} --no-open
