/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as gfeTestimonialCardImport } from './routes/(gfe)/testimonial-card'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const gfeTestimonialCardRoute = gfeTestimonialCardImport.update({
  id: '/(gfe)/testimonial-card',
  path: '/testimonial-card',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(gfe)/testimonial-card': {
      id: '/(gfe)/testimonial-card'
      path: '/testimonial-card'
      fullPath: '/testimonial-card'
      preLoaderRoute: typeof gfeTestimonialCardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testimonial-card': typeof gfeTestimonialCardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testimonial-card': typeof gfeTestimonialCardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(gfe)/testimonial-card': typeof gfeTestimonialCardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testimonial-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testimonial-card'
  id: '__root__' | '/' | '/(gfe)/testimonial-card'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  gfeTestimonialCardRoute: typeof gfeTestimonialCardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  gfeTestimonialCardRoute: gfeTestimonialCardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(gfe)/testimonial-card"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(gfe)/testimonial-card": {
      "filePath": "(gfe)/testimonial-card.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
