/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GfeRouteRouteImport } from './routes/_gfe/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GfeTestimonialCardIndexRouteImport } from './routes/_gfe/testimonial-card/index'
import { Route as GfeProfileCardIndexRouteImport } from './routes/_gfe/profile-card/index'
import { Route as GfeBlogCardIndexRouteImport } from './routes/_gfe/blog-card/index'

const GfeRouteRoute = GfeRouteRouteImport.update({
  id: '/_gfe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GfeTestimonialCardIndexRoute = GfeTestimonialCardIndexRouteImport.update({
  id: '/testimonial-card/',
  path: '/testimonial-card/',
  getParentRoute: () => GfeRouteRoute,
} as any)
const GfeProfileCardIndexRoute = GfeProfileCardIndexRouteImport.update({
  id: '/profile-card/',
  path: '/profile-card/',
  getParentRoute: () => GfeRouteRoute,
} as any)
const GfeBlogCardIndexRoute = GfeBlogCardIndexRouteImport.update({
  id: '/blog-card/',
  path: '/blog-card/',
  getParentRoute: () => GfeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog-card': typeof GfeBlogCardIndexRoute
  '/profile-card': typeof GfeProfileCardIndexRoute
  '/testimonial-card': typeof GfeTestimonialCardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog-card': typeof GfeBlogCardIndexRoute
  '/profile-card': typeof GfeProfileCardIndexRoute
  '/testimonial-card': typeof GfeTestimonialCardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gfe': typeof GfeRouteRouteWithChildren
  '/_gfe/blog-card/': typeof GfeBlogCardIndexRoute
  '/_gfe/profile-card/': typeof GfeProfileCardIndexRoute
  '/_gfe/testimonial-card/': typeof GfeTestimonialCardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog-card' | '/profile-card' | '/testimonial-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog-card' | '/profile-card' | '/testimonial-card'
  id:
    | '__root__'
    | '/'
    | '/_gfe'
    | '/_gfe/blog-card/'
    | '/_gfe/profile-card/'
    | '/_gfe/testimonial-card/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GfeRouteRoute: typeof GfeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gfe': {
      id: '/_gfe'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GfeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gfe/testimonial-card/': {
      id: '/_gfe/testimonial-card/'
      path: '/testimonial-card'
      fullPath: '/testimonial-card'
      preLoaderRoute: typeof GfeTestimonialCardIndexRouteImport
      parentRoute: typeof GfeRouteRoute
    }
    '/_gfe/profile-card/': {
      id: '/_gfe/profile-card/'
      path: '/profile-card'
      fullPath: '/profile-card'
      preLoaderRoute: typeof GfeProfileCardIndexRouteImport
      parentRoute: typeof GfeRouteRoute
    }
    '/_gfe/blog-card/': {
      id: '/_gfe/blog-card/'
      path: '/blog-card'
      fullPath: '/blog-card'
      preLoaderRoute: typeof GfeBlogCardIndexRouteImport
      parentRoute: typeof GfeRouteRoute
    }
  }
}

interface GfeRouteRouteChildren {
  GfeBlogCardIndexRoute: typeof GfeBlogCardIndexRoute
  GfeProfileCardIndexRoute: typeof GfeProfileCardIndexRoute
  GfeTestimonialCardIndexRoute: typeof GfeTestimonialCardIndexRoute
}

const GfeRouteRouteChildren: GfeRouteRouteChildren = {
  GfeBlogCardIndexRoute: GfeBlogCardIndexRoute,
  GfeProfileCardIndexRoute: GfeProfileCardIndexRoute,
  GfeTestimonialCardIndexRoute: GfeTestimonialCardIndexRoute,
}

const GfeRouteRouteWithChildren = GfeRouteRoute._addFileChildren(
  GfeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GfeRouteRoute: GfeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
